author: andreadelfante
author_url: https://twitter.com/a_delfante
github_url: https://github.com/andreadelfante/PredicateFlow
root_url: https://andreadelfante.github.io/PredicateFlow
module: PredicateFlow
output: docs
theme: fullwidth
clean: true

xcodebuild_arguments:
    - "-workspace"
    - "Example/PredicateFlow.xcworkspace"
    - "-scheme"
    - "PredicateFlow-Example"
