# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

cache:
  - bundler
  - cocoapods
  directories:
  - ./build

jobs:
  include:
    - stage: lint
      script: bundle exec fastlane linting
    - stage: test
      script: bundle exec fastlane test
