# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

install:
  - bundle install

jobs:
  include:
    - stage: prepare
      script: bundle exec fastlane prepare
    - stage: lint
      script: bundle exec fastlane swiftlinting
      script: bundle exec fastlane podlinting
    - stage: test
      script: bundle exec fastlane test
    - stage: docs
      script: bundle exec fastlane documentation
    - deploy:
        provider: script
        script: bundle exec fastlane deploy
        on:
          branch: master
